PRODUCT_COPY_FILES += \
    vendor/amazon/bueller/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/amazon/bueller/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/amazon/bueller/proprietary/bin/diag_callback_client:system/bin/diag_callback_client \
    vendor/amazon/bueller/proprietary/bin/diag_dci_client:system/bin/diag_dci_client \
    vendor/amazon/bueller/proprietary/bin/diag_klog:system/bin/diag_klog \
    vendor/amazon/bueller/proprietary/bin/diag_socket_log:system/bin/diag_socket_log \
    vendor/amazon/bueller/proprietary/bin/diag_uart_log:system/bin/diag_uart_log \
    vendor/amazon/bueller/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/amazon/bueller/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/amazon/bueller/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/amazon/bueller/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/amazon/bueller/proprietary/bin/thermald:system/bin/thermald \
    vendor/amazon/bueller/proprietary/etc/DxHDCP.cfg:system/etc/DxHDCP.cfg \
    vendor/amazon/bueller/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/amazon/bueller/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/amazon/bueller/proprietary/etc/firmware/ath6k/AR6004/hw3.0/bdata.bin:system/etc/firmware/ath6k/AR6004/hw3.0/bdata.bin \
    vendor/amazon/bueller/proprietary/etc/firmware/ath6k/AR6004/hw3.0/fw.ram.bin:system/etc/firmware/ath6k/AR6004/hw3.0/fw.ram.bin \
    vendor/amazon/bueller/proprietary/etc/firmware/tz_skp.b00:system/etc/firmware/tz_skp.b00 \
    vendor/amazon/bueller/proprietary/etc/firmware/tz_skp.b01:system/etc/firmware/tz_skp.b01 \
    vendor/amazon/bueller/proprietary/etc/firmware/tz_skp.b02:system/etc/firmware/tz_skp.b02 \
    vendor/amazon/bueller/proprietary/etc/firmware/tz_skp.b03:system/etc/firmware/tz_skp.b03 \
    vendor/amazon/bueller/proprietary/etc/firmware/tz_skp.mdt:system/etc/firmware/tz_skp.mdt \
    vendor/amazon/bueller/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/amazon/bueller/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/amazon/bueller/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/amazon/bueller/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/amazon/bueller/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/amazon/bueller/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/amazon/bueller/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/amazon/bueller/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/amazon/bueller/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/amazon/bueller/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/amazon/bueller/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/amazon/bueller/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/amazon/bueller/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/amazon/bueller/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/amazon/bueller/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/amazon/bueller/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/amazon/bueller/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/amazon/bueller/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/amazon/bueller/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/amazon/bueller/proprietary/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
    vendor/amazon/bueller/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/amazon/bueller/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/amazon/bueller/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/amazon/bueller/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/amazon/bueller/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/amazon/bueller/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/amazon/bueller/proprietary/lib/libDxHdcp.so:system/lib/libDxHdcp.so \
    vendor/amazon/bueller/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/amazon/bueller/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/amazon/bueller/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/amazon/bueller/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
    vendor/amazon/bueller/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/amazon/bueller/proprietary/lib/libqc-opt.so.org:system/lib/libqc-opt.so.org \
    vendor/amazon/bueller/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/amazon/bueller/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/amazon/bueller/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/amazon/bueller/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/amazon/bueller/proprietary/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
    vendor/amazon/bueller/proprietary/lib/libWVStreamControlAPI_L1.so:system/lib/libWVStreamControlAPI_L1.so \
    vendor/amazon/bueller/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/amazon/bueller/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/amazon/bueller/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/amazon/bueller/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
